language: emacs-lisp
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  - sudo apt-get update -y -q
  - sudo apt-get install emacs24-nox emacs-snapshot-nox
install:
  - $EMACS -batch -f batch-byte-compile parent-mode.el
script:
  - $EMACS -batch -l parent-mode-test.el -f ert-run-tests-batch-and-exit